
  CREATE TABLE "IDAF"."TAB_PROTOCOLO_ASSINANTES" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROTOCOLO" NUMBER(38,0) NOT NULL ENABLE, 
	"FUNCIONARIO" NUMBER(38,0) NOT NULL ENABLE, 
	"CARGO" NUMBER(38,0), 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PROTOCOLO_ASSINANTES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_PROTOCOLO_ASS_CAR" FOREIGN KEY ("CARGO")
	  REFERENCES "IDAF"."TAB_CARGO" ("ID") ENABLE, 
	 CONSTRAINT "FK_PROTOCOLO_ASS_FUN" FOREIGN KEY ("FUNCIONARIO")
	  REFERENCES "IDAF"."TAB_FUNCIONARIO" ("ID") ENABLE, 
	 CONSTRAINT "FK_PROTOCOLO_ASS_TIT" FOREIGN KEY ("PROTOCOLO")
	  REFERENCES "IDAF"."TAB_PROTOCOLO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO_ASSINANTES"."ID" IS 'Chave primaria. Utiliza a sequencia seq_protocolo_assinantes.';
 
   COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO_ASSINANTES"."PROTOCOLO" IS 'Chave estrangeira para tab_protocolo. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO_ASSINANTES"."FUNCIONARIO" IS 'Chave estrangeira para tab_funcionario. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO_ASSINANTES"."CARGO" IS 'Chave estrangeira para tab_cargo. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO_ASSINANTES"."TID" IS 'Id transacional. Esse valor garante a ligacao entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_PROTOCOLO_ASSINANTES"  IS 'Tabela de relacionamento dos assinante com o protocolo.';
 

  CREATE INDEX "IDAF"."IDX_PROTOCOLO_ASS_FUN" ON "IDAF"."TAB_PROTOCOLO_ASSINANTES" ("FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_PROTOCOLO_ASS_TID" ON "IDAF"."TAB_PROTOCOLO_ASSINANTES" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_PROTOCOLO_ASS_TIT" ON "IDAF"."TAB_PROTOCOLO_ASSINANTES" ("PROTOCOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;