  ALTER TABLE TAB_PROTOCOLO ADD DESTINATARIO NUMBER(38,0);
  ALTER TABLE TAB_PROTOCOLO ADD DESTINATARIO_SETOR NUMBER(38,0);
  
  ALTER TABLE HST_PROTOCOLO ADD DESTINATARIO_ID NUMBER(38,0);
	ALTER TABLE HST_PROTOCOLO ADD DESTINATARIO_TID VARCHAR2(36 BYTE);
	ALTER TABLE HST_PROTOCOLO ADD DESTINATARIO_SETOR_ID NUMBER(38,0);
	ALTER TABLE HST_PROTOCOLO ADD DESTINATARIO_SETOR_TID VARCHAR2(36 BYTE);
    
  ALTER TABLE TAB_PROTOCOLO ADD CONSTRAINT "FK_PROTOC_DESTINO" FOREIGN KEY ("DESTINATARIO")
	  REFERENCES "IDAF"."TAB_FUNCIONARIO" ("ID") ENABLE;
  ALTER TABLE TAB_PROTOCOLO ADD CONSTRAINT "FK_PROTOC_DES_SETOR" FOREIGN KEY ("DESTINATARIO_SETOR")
	  REFERENCES "IDAF"."TAB_SETOR" ("ID") ENABLE;    
    
  COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO"."DESTINATARIO" IS 'Chave estrangeira para tab_funcionario. Campo(ID).'; 
  COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO"."DESTINATARIO_SETOR" IS 'Chave estrangeira para tab_setor. Campo(ID).';  
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."DESTINATARIO_ID" IS 'Chave estrangeira para tab_funcionario. Campo(ID).';
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."DESTINATARIO_TID" IS 'Referencia ao campo (TID) da tabela tab_funcionario.';
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."DESTINATARIO_SETOR_ID" IS 'Chave estrangeira para tab_setor. Campo(ID).';
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."DESTINATARIO_SETOR_TID" IS 'Referencia ao campo (TID) da tabela tab_setor.';