ALTER TABLE TAB_FISC_COBRANCA ADD NUMERO_AUTUACAO VARCHAR2(15 BYTE);
COMMENT ON COLUMN "IDAF"."TAB_FISC_COBRANCA"."NUMERO_AUTUACAO" IS 'Numero da autuacao. Obtido junto ao prodest.';
ALTER TABLE TAB_FISC_COBRANCA DROP COLUMN AUTOS;
COMMIT;