  CREATE TABLE "IDAF"."LOV_FISC_PENALIDADES_FIXAS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TEXTO" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PEN_FIX" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."LOV_FISC_PENALIDADES_FIXAS"."ID" IS 'Chave primaria.';
 
   COMMENT ON COLUMN "IDAF"."LOV_FISC_PENALIDADES_FIXAS"."TEXTO" IS 'Descrição da penalidade.';
   
   COMMENT ON TABLE "IDAF"."LOV_FISC_PENALIDADES_FIXAS"  IS 'Tabela de penalidades fixas da Infração, aba Infração/Fiscalização.';
 
 
