  CREATE TABLE "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INFRACAO" NUMBER(38,0) NOT NULL ENABLE,
	"PENALIDADE_OUTRA" NUMBER(38, 0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_OP_INFR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_FIS_OP_INF" FOREIGN KEY ("INFRACAO")
	  REFERENCES "IDAF"."TAB_FISC_INFRACAO" ("ID") ENABLE,
	 CONSTRAINT "FK_FIS_OP_CNF" FOREIGN KEY ("PENALIDADE_OUTRA")
	  REFERENCES "IDAF"."CNF_FISC_INFRACAO_PENALIDADE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR"."ID" IS 'Chave primaria. Utiliza a sequencia seq_outras_penalidad_infr.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR"."INFRACAO" IS 'Chave estrangeira para tab_fisc_infracao. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR"."PENALIDADE_OUTRA" IS 'Chave estrangeira para cnf_fisc_infracao_penalidade.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR"  IS 'Tabela da Fiscalização que relaciona uma Infração à uma Penalidade cadastrada na tela de configurações de penalidade.';
 

  CREATE INDEX "IDAF"."IDX_FIS_OP_INF_INF" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR" ("INFRACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_OP_INF_OP" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR" ("PENALIDADE_OUTRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_OP_INF_TID" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDAD_INFR" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
