
  CREATE TABLE "IDAF"."HST_FISC_OUTRAS_PENALIDADES" 
  (	"ID" 					NUMBER(38,0) NOT NULL ENABLE, 
	"ID_HST" 				NUMBER(38,0) NOT NULL ENABLE, 
	"OUTRAS_PENALIDADES_ID"	NUMBER(38,0), 
	"FISCALIZACAO_ID" 		NUMBER(38,0),
	"IUF_DIGITAL"			NUMBER(1,0),
	"IUF_NUMERO"			NUMBER(38,0),
	"IUF_DATA"				DATE,
	"ARQUIVO_ID"			NUMBER(38,0),
	"ARQUIVO_TID" 			VARCHAR2(36 BYTE),
	"SERIE_ID"				NUMBER(38,0),
	"SERIE_TEXTO"			VARCHAR2(50 BYTE),
	"DESCRICAO" 			VARCHAR2(3000 BYTE),
	"TID"					VARCHAR2(36 BYTE)	NOT NULL,  
  CONSTRAINT "PK_HST_FISC_OUT_PEN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_FISC_OP_HST" FOREIGN KEY ("ID_HST")
	  REFERENCES "IDAF"."HST_FISCALIZACAO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."ID" 					   IS 'Chave primaria. Utiliza a sequencia SEQ_HST_FISC_OUTRAS_PENAL.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."ID_HST" 				   IS 'Chave estrangeira para hst_fiscalizacao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."OUTRAS_PENALIDADES_ID"   IS 'Chave estrangeira para tab_fisc_outras_oenalidades. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."FISCALIZACAO_ID" 		   IS 'Chave estrangeira para tab_fiscalizacao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."IUF_DIGITAL"			   IS 'Informa se IUF é digital ou bloco. 1 - digital | 0 - bloco.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."IUF_NUMERO"			   IS 'Informa o número do IUF.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."IUF_DATA"				   IS 'Data do IUF.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."ARQUIVO_ID"			   IS 'Chave estrangeira para tab_arquivo. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."ARQUIVO_TID" 			   IS 'Referencia ao campo (TID) da tabela tab_arquivo.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."SERIE_ID"				   IS 'Chave estrangeira para lov_fiscalizacao_serie. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."SERIE_TEXTO"			   IS 'Série utilizada. Campo (TEXTO) da tabela lov_fiscalizacao_serie.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."DESCRICAO" 			   IS 'Descrição da penalidade.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDADES"."TID"					   IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_OUTRAS_PENALIDADES"  IS 'Tabela com o histórico da tabela tab_fisc_outras_penalidades da Fiscalização.';
 

  CREATE INDEX "IDAF"."IDX_HST_OP_ARQ" ON "IDAF"."HST_FISC_OUTRAS_PENALIDADES" ("ARQUIVO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_OP_FISC" ON "IDAF"."HST_FISC_OUTRAS_PENALIDADES" ("FISCALIZACAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_OP_HST" ON "IDAF"."HST_FISC_OUTRAS_PENALIDADES" ("ID_HST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_OP_TID" ON "IDAF"."HST_FISC_OUTRAS_PENALIDADES" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
