
  CREATE TABLE "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR" 
  (	"ID" 					NUMBER(38,0) NOT NULL ENABLE, 
	"ID_HST" 				NUMBER(38,0) NOT NULL ENABLE, 
	"OUTRAS_PEN_INFR_ID"	NUMBER(38,0), 
	"INFRACAO_ID"	 		NUMBER(38,0),
	"PEN_OUTR_ID"			NUMBER(1,0),
	"PEN_OUTR_TID"			VARCHAR2(36 BYTE),
	"PEN_OUTR_ARTIGO"		VARCHAR2(10 BYTE),
	"PEN_OUTR_ITEM"			VARCHAR2(10 BYTE),
	"PEN_OUTR_DESCRICAO"	VARCHAR2(200 BYTE),
	"TID"					VARCHAR2(36 BYTE)	NOT NULL,  
  CONSTRAINT "PK_HST_FISC_OUT_PEN_INFR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_FISC_OP_INFR_HST" FOREIGN KEY ("ID_HST")
	  REFERENCES "IDAF"."HST_FISC_INFRACAO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."ID" 				   IS 'Chave primaria. Utiliza a sequencia seq_hst_fisc_outr_penali_infr.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."ID_HST" 			   IS 'Chave estrangeira para hst_fisc_infracao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."OUTRAS_PEN_INFR_ID"  IS 'Chave estrangeira para tab_fisc_outras_penalidad_infr. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."INFRACAO_ID"	 	   IS 'Chave estrangeira para tab_fisc_infracao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."PEN_OUTR_ID"		   IS 'Chave estrangeira para cnf_fisc_infracao_penalidade. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."PEN_OUTR_TID"		   IS 'Referencia o campo TID da tabela cnf_fisc_infracao_penalidade.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."PEN_OUTR_ARTIGO"	   IS 'Artigo da penalida.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."PEN_OUTR_ITEM"	   IS 'Item da penalidade.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."PEN_OUTR_DESCRICAO"  IS 'Descrição da penalidade.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"."TID"				   IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR"  IS 'Tabela com o histórico da tabela tab_fisc_outras_penalidad_infr da Fiscalização.';
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_OP_INFR" ON "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR" ("INFRACAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_OPINFR_HST" ON "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR" ("ID_HST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  
  CREATE INDEX "IDAF"."IDX_HST_FISC_OPINFR_PEN" ON "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR" ("PEN_OUTR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_OPINFR_TID" ON "IDAF"."HST_FISC_OUTRAS_PENALIDAD_INFR" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
