
  CREATE TABLE "IDAF"."HST_FISC_PENALIDADES_INFR" 
  (	"ID" 					NUMBER(38,0) NOT NULL ENABLE, 
	"ID_HST" 				NUMBER(38,0) NOT NULL ENABLE, 
	"PENALIDADES_INFR_ID"	NUMBER(38,0), 
	"INFRACAO_ID"	 		NUMBER(38,0),
	"PENALIDADE_ID"			NUMBER(1,0),
	"PENALIDADE_TEXTO"		VARCHAR2(1000 BYTE),
	"TID"					VARCHAR2(36 BYTE)	NOT NULL,  
  CONSTRAINT "PK_HST_FISC_PEN_INFR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_FISC_PEN_INFR_HST" FOREIGN KEY ("ID_HST")
	  REFERENCES "IDAF"."HST_FISC_INFRACAO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."ID" 					  IS 'Chave primaria. Utiliza a sequencia seq_hst_fisc_penalidades_infr.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."ID_HST" 				  IS 'Chave estrangeira para hst_fisc_infracao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."PENALIDADES_INFR_ID"	  IS 'Chave estrangeira para tab_fisc_penalidades_infr. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."INFRACAO_ID"	 		  IS 'Chave estrangeira para tab_fisc_infracao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."PENALIDADE_ID"		  IS 'Chave estrangeira para lov_fisc_penalidades_fixas. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."PENALIDADE_TEXTO"		  IS 'Descrição da penalidade.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PENALIDADES_INFR"."TID"					  IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_PENALIDADES_INFR"  IS 'Tabela com o histórico da tabela tab_fisc_penalidades_infr da Fiscalização.';
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_PEN_INFR" ON "IDAF"."HST_FISC_PENALIDADES_INFR" ("INFRACAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_PENINFR_HST" ON "IDAF"."HST_FISC_PENALIDADES_INFR" ("ID_HST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  
  CREATE INDEX "IDAF"."IDX_HST_FISC_PENINFR_PEN" ON "IDAF"."HST_FISC_PENALIDADES_INFR" ("PENALIDADE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_PENINFR_TID" ON "IDAF"."HST_FISC_PENALIDADES_INFR" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
