
  CREATE TABLE "IDAF"."HST_FISC_APREENSAO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ID_HST" NUMBER(38,0) NOT NULL ENABLE, 
	"APREENSAO_ID"	NUMBER(38,0), 
	"FISCALIZACAO_ID" NUMBER(38,0),
  "IUF_DIGITAL"	NUMBER(1,0),
  "IUF_NUMERO"	NUMBER(38,0),
  "IUF_DATA"	DATE,
  "NUMERO_LACRES"	VARCHAR2(250 BYTE),
  "ARQUIVO_ID"	NUMBER(38,0),
  "ARQUIVO_TID" VARCHAR2(36 BYTE),
  "SERIE_ID"	NUMBER(38,0),
  "SERIE_TEXTO"	VARCHAR2(50 BYTE),
  "DESCRICAO"	VARCHAR2(1000 BYTE),
  "VALOR_PRODUTOS"	VARCHAR2(250 BYTE),
  "DEPOSITARIO_ID"	NUMBER(38,0),
  "DEPOSITARIO_NOME" VARCHAR2(500 BYTE),
  "DEPOSITARIO_CPF" VARCHAR2(14 BYTE),
  "ENDERECO_LOGRADOURO"	VARCHAR2(500 BYTE),
  "ENDERECO_BAIRRO"	VARCHAR2(100 BYTE),
  "ENDERECO_DISTRITO"	VARCHAR2(100 BYTE),
  "ENDERECO_ESTADO_ID"	NUMBER(38,0),
  "ENDERECO_ESTADO"	VARCHAR(250 BYTE),
  "ENDERECO_MUNICIPIO_ID"	NUMBER(38,0),
  "ENDERECO_MUNICIPIO"	VARCHAR(250),
  "OPINIAO"	VARCHAR2(250 BYTE),
  "VALOR_PRODUTOS_REAIS"	NUMBER,
  "TID"	VARCHAR2(36 BYTE)	NOT NULL,  
  CONSTRAINT "PK_HST_FISC_APREENSAO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_FISC_APREENSAO_HST" FOREIGN KEY ("ID_HST")
	  REFERENCES "IDAF"."HST_FISCALIZACAO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."ID"						IS 'Chave primaria. Utiliza a sequencia SEQ_TAB_FISC_APREENSAO.';
	COMMENT ON COLUMN "IDAF"."ID_HST"                   IS 'Chave estrangeira para hst_fiscalizacao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."APREENSAO_ID"             IS 'Chave estrangeira para tab_fisc_apreensao. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."FISCALIZACAO_ID"          IS 'Chave estrangeira para tab_fiscalizacao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."IUF_DIGITAL"              IS 'Informa se IUF é digital ou bloco. 1 - digital | 0 - bloco.';
	COMMENT ON COLUMN "IDAF"."IUF_NUMERO"               IS 'Informa o número do IUF.';
	COMMENT ON COLUMN "IDAF"."IUF_DATA"                 IS 'Data do IUF.';
	COMMENT ON COLUMN "IDAF"."NUMERO_LACRES"            IS 'Números dos lacres utilizados na apreensão.';
	COMMENT ON COLUMN "IDAF"."ARQUIVO_ID"               IS 'Chave estrangeira para tab_arquivo. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."ARQUIVO_TID"              IS 'Referencia ao campo (TID) da tabela tab_arquivo.';
	COMMENT ON COLUMN "IDAF"."SERIE_ID"                 IS 'Chave estrangeira para lov_fiscalizacao_serie. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."SERIE_TEXTO"              IS 'Série utilizada. Campo (TEXTO) da tabela lov_fiscalizacao_serie.';
	COMMENT ON COLUMN "IDAF"."DESCRICAO"                IS 'Descrição da apreensão.';
	COMMENT ON COLUMN "IDAF"."VALOR_PRODUTOS"           IS 'Valor dos produtos/bens apreeendidos, em reais e por extenso.';
	COMMENT ON COLUMN "IDAF"."DEPOSITARIO_ID"           IS 'Chave estrangeira para tab_pessoa. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."DEPOSITARIO_NOME"         IS 'Nome do depositário.';
	COMMENT ON COLUMN "IDAF"."DEPOSITARIO_CPF"          IS 'CPF do depositário.';
	COMMENT ON COLUMN "IDAF"."ENDERECO_LOGRADOURO"      IS 'Logradouro do depositario.';
	COMMENT ON COLUMN "IDAF"."ENDERECO_BAIRRO"          IS 'Bairro do depositario.';
	COMMENT ON COLUMN "IDAF"."ENDERECO_DISTRITO"        IS 'Distrito do depositario.';
	COMMENT ON COLUMN "IDAF"."ENDERECO_ESTADO_ID"       IS 'Chave estrangeira para lov_estado. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."ENDERECO_ESTADO"          IS 'UF do depositário.';
	COMMENT ON COLUMN "IDAF"."ENDERECO_MUNICIPIO_ID"    IS 'Chave estrangeira para lov_municipio. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."ENDERECO_MUNICIPIO"       IS 'Município do depositário.';
	COMMENT ON COLUMN "IDAF"."OPINIAO"                  IS 'Opinar pelo destino do material e/ou bens apreendido.';
	COMMENT ON COLUMN "IDAF"."VALOR_PRODUTOS_REAIS"     IS 'Valor dos produtos, em reais.';
	COMMENT ON COLUMN "IDAF"."TID"                      IS 'Id transacional. Esse valor garante a ligac?o entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_APREENSAO"  IS 'Tabela com o histórico da tabela tab_fisc_apreensao da Fiscalização.';
 

  CREATE INDEX "IDAF"."IDX_HST_APREENSAO_ARQ" ON "IDAF"."HST_FISC_APREENSAO" ("ARQUIVO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_APREENSAO_FISC" ON "IDAF"."HST_FISC_APREENSAO" ("FISCALIZACAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_APREENSAO_HST" ON "IDAF"."HST_FISC_APREENSAO" ("ID_HST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_APREENSAO_TID" ON "IDAF"."HST_FISC_APREENSAO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
