
  CREATE TABLE "IDAF"."HST_FISC_CONSID_FINAL_IUF" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ID_HST" NUMBER(38,0) NOT NULL ENABLE, 
	"CONSID_FINAL_IUF_ID" NUMBER(38,0), 
	"CONSID_FINAL_ID" NUMBER(38,0), 
	"ARQUIVO_ID" NUMBER(38,0), 
	"ARQUIVO_TID" VARCHAR2(36 BYTE), 
	"ORDEM" NUMBER(3,0), 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_H_FISC_CONSID_FINAL_IUF" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_H_FISC_CONSID_FINAL_IUFH" FOREIGN KEY ("ID_HST")
	  REFERENCES "IDAF"."HST_FISC_CONSID_FINAL" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."ID" IS 'Chave primaria. Utiliza a sequencia SEQ_HST_FISC_CONSID_FINAL_IUF.';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."ID_HST" IS 'Chave estrangeira para hst_fisc_consid_final. Campo(ID).';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."CONSID_FINAL_IUF_ID" IS 'Chave estrangeira para tab_fisc_consid_final_iuf. Campo(ID).';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."CONSID_FINAL_ID" IS 'Chave estrangeira para tab_fisc_consid_final. Campo(ID).';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."ARQUIVO_ID" IS 'Chave estrangeira para tab_arquivo. Campo(ID).';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."ARQUIVO_TID" IS 'Referencia ao campo (TID) da tabela tab_arquivo.';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."ORDEM" IS 'Ordem de inserção do item na lista.';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."DESCRICAO" IS 'Descrição do arquivo inserido na lista.';
   COMMENT ON COLUMN "IDAF"."HST_FISC_CONSID_FINAL_IUF"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."HST_FISC_CONSID_FINAL_IUF"  IS 'Tabela de relacionamento do historico da fiscalização e seus arquivos IUF.';
 

  CREATE INDEX "IDAF"."IDX_FISC_CONS_F_IUF_ARQ_ID" ON "IDAF"."HST_FISC_CONSID_FINAL_IUF" ("ARQUIVO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FISC_CONS_F_IUF_ARQ_TID" ON "IDAF"."HST_FISC_CONSID_FINAL_IUF" ("ARQUIVO_TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 655360 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FISC_CONS_F_IUF_ID" ON "IDAF"."HST_FISC_CONSID_FINAL_IUF" ("CONSID_FINAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FISC_CONS_F_IUF_ID_HST" ON "IDAF"."HST_FISC_CONSID_FINAL_IUF" ("ID_HST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FISC_CONS_F_IUF_ID_TAB" ON "IDAF"."HST_FISC_CONSID_FINAL_IUF" ("CONSID_FINAL_IUF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FISC_CONS_F_IUF_TID" ON "IDAF"."HST_FISC_CONSID_FINAL_IUF" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
