
  CREATE TABLE "IDAF"."TAB_FISC_PENALIDADES_INFR" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INFRACAO" NUMBER(38,0) NOT NULL ENABLE,
	"PENALIDADE" NUMBER(38, 0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PEN_INFR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_FIS_PEN_INF" FOREIGN KEY ("INFRACAO")
	  REFERENCES "IDAF"."TAB_FISC_INFRACAO" ("ID") ENABLE,
	 CONSTRAINT "FK_FIS_PEN_LOV" FOREIGN KEY ("PENALIDADE")
	  REFERENCES "IDAF"."LOV_FISC_PENALIDADES_FIXAS" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_FISC_PENALIDADES_INFR"."ID" IS 'Chave primaria. Utiliza a sequencia seq_fisc_penalidades_infr.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_PENALIDADES_INFR"."INFRACAO" IS 'Chave estrangeira para tab_fisc_infracao. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_PENALIDADES_INFR"."PENALIDADE" IS 'Chave estrangeira para lov_fisc_penalidades_fixas.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_PENALIDADES_INFR"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_FISC_PENALIDADES_INFR"  IS 'Tabela da Fiscalização que relaciona uma Infração à uma Penalidade.';
 

  CREATE INDEX "IDAF"."IDX_FIS_PEN_INF_INF" ON "IDAF"."TAB_FISC_PENALIDADES_INFR" ("INFRACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_PEN_INF_PEN" ON "IDAF"."TAB_FISC_PENALIDADES_INFR" ("PENALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_PEN_INF_TID" ON "IDAF"."TAB_FISC_PENALIDADES_INFR" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
