  CREATE TABLE "IDAF"."TAB_FISC_VRTE"
  (
    "ID"                NUMBER(38,0) NOT NULL ENABLE,
    "ANO"               NUMBER(4,0) NOT NULL ENABLE,
    "VRTE"              NUMBER(15,4) NOT NULL ENABLE,
    "TID"              VARCHAR2(36 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_FIS_VRTE" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "IDAF_TBS" ;
 
  COMMENT ON COLUMN "IDAF"."TAB_FISC_VRTE"."ID" IS 'Chave primaria. Utiliza a sequencia seq_fisc_vrte.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_VRTE"."ANO" IS 'Informa o ano de vigência do VRTE';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_VRTE"."VRTE" IS 'Informa o VRTE.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_VRTE"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
  
  COMMENT ON TABLE "IDAF"."TAB_FISC_VRTE"  IS 'Tabela de VRTE.';
 
  CREATE INDEX "IDAF"."IDX_FIS_VRTE_TID" ON "IDAF"."TAB_FISC_VRTE" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
