
  CREATE TABLE "IDAF"."HST_FISC_VRTE" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
  "VRTE_ID" NUMBER(38,0) NOT NULL ENABLE, 
  "ANO" NUMBER(4,0),
  "VRTE" NUMBER(15,4),  
  "TID"	VARCHAR2(36 BYTE)	NOT NULL,  
  "EXECUTOR_ID" NUMBER(38,0), 
	"EXECUTOR_TID" VARCHAR2(36 BYTE), 
	"EXECUTOR_NOME" VARCHAR2(80 BYTE), 
	"EXECUTOR_LOGIN" VARCHAR2(30 BYTE), 
	"EXECUTOR_TIPO_ID" NUMBER(38,0), 
	"EXECUTOR_TIPO_TEXTO" VARCHAR2(30 BYTE), 
	"ACAO_EXECUTADA" NUMBER(38,0) NOT NULL ENABLE, 
	"DATA_EXECUCAO" TIMESTAMP (6) NOT NULL ENABLE,
  CONSTRAINT "PK_HST_FISC_VRTE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_VRTE"."ID"	IS 'Chave primaria. Utiliza a sequencia seq_hst_fisc_vrte.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_VRTE"."VRTE_ID" IS 'Campo Id da tabela tab_fisc_vrte.';	
	COMMENT ON COLUMN "IDAF"."HST_FISC_VRTE"."ANO" IS 'Informa o ano de vigência do VRTE';  
  COMMENT ON COLUMN "IDAF"."HST_FISC_VRTE"."VRTE" IS 'Informa o VRTE.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_VRTE"."TID" IS 'Id transacional. Esse valor garante a ligacao entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_VRTE"  IS 'Tabela com o historico da tabela tab_fisc_vrte da Fiscalizacao.';
 
  CREATE INDEX "IDAF"."IDX_HST_FISC_VRTE_TID" ON "IDAF"."HST_FISC_VRTE" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
