
  CREATE TABLE "IDAF"."HST_FISC_APREENSAO_PRODUTO" 
  (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ID_HST" NUMBER(38,0) NOT NULL ENABLE,
	"APREENSAO_PROD_ID" NUMBER(38,0),
	"APREENSAO_ID"	NUMBER(38,0), 
	"APREENSAO_TID" VARCHAR2(36 BYTE),  
	"PRODUTO_ID" NUMBER(38, 0),
	"PRODUTO_TID"	VARCHAR2(36 BYTE) NOT NULL,  
	"PRODUTO_ITEM" VARCHAR2(100 BYTE),
	"PRODUTO_UNIDADE" VARCHAR2(50 BYTE),
	"QUANTIDADE" NUMBER,
	"DESTINACAO_ID" NUMBER(38,0),
	"DESTINACAO_TID"	VARCHAR2(36 BYTE) NOT NULL,  
	"DESTINACAO_DESTINO" VARCHAR2(100 BYTE),
	"TID" VARCHAR2(36 BYTE) NOT NULL,  
  CONSTRAINT "PK_HST_FISC_APREENSAO_PROD" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_FISC_APREEN_PROD_HST" FOREIGN KEY ("ID_HST")
	  REFERENCES "IDAF"."HST_FISC_APREENSAO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."ID"							IS 'Chave primaria. Utiliza a sequencia SEQ_HST_FISC_APREENSAO_PROD.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."ID_HST"						IS 'Chave estrangeira para hst_fisc_apreensao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."APREENSAO_PROD_ID"			IS 'Chave estrangeira para TAB_FISC_APREENSAO_PRODUTO. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."APREENSAO_ID"					IS 'Chave estrangeira para tab_fisc_apreensao. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."APREENSAO_TID"				IS 'Campo TID da tabela tab_fisc_apreensao.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."PRODUTO_ID"					IS 'Chave estrangeira para CNF_FISC_INFRACAO_PRODUTO. Campo (ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."PRODUTO_TID"					IS 'Campo TID da tabela CNF_FISC_INFRACAO_PRODUTO.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."PRODUTO_ITEM"					IS 'Descrição do produto apreendido.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."PRODUTO_UNIDADE"				IS 'Unidade do produto apreendido.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."QUANTIDADE"					IS 'Quantida do produto apreendido.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."DESTINACAO_ID"				IS 'Chave estrangeira para CNF_FISC_INFR_DESTINACAO. Campo(ID).';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."DESTINACAO_TID"	    		IS 'Campo TID da tabela CNF_FISC_INFR_DESTINACAO.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."DESTINACAO_DESTINO"			IS 'Descrição do destino.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_APREENSAO_PRODUTO"."TID"							IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_APREENSAO_PRODUTO"	IS 'Tabela com o histórico da tabela tab_fisc_apreensao_produto da Fiscalização.';
 

  CREATE INDEX "IDAF"."IDX_HST_APREEN_PROD_APR_HST" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("ID_HST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_APREEN_PROD_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("APREENSAO_PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_APREENSAO_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("APREENSAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_APREENTID_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("APREENSAO_TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_PRODUTO_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("PRODUTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_PRODTID_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("PRODUTO_TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_DESTINACAO_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("DESTINACAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_DESTINTID_HST_APR_PROD" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("DESTINACAO_TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_FISC_APR_PROD_TID" ON "IDAF"."HST_FISC_APREENSAO_PRODUTO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
