
  CREATE TABLE "IDAF"."TAB_FISC_APREENSAO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"FISCALIZACAO" NUMBER(38,0) NOT NULL ENABLE, 
	"IUF_DIGITAL" NUMBER(1,0) NOT NULL ENABLE, 
	"IUF_NUMERO" NUMBER(38,0), 
	"IUF_DATA" DATE, 
	"NUMERO_LACRES" VARCHAR2(250 BYTE), 
	"ARQUIVO" NUMBER(38,0), 
	"SERIE" NUMBER(38,0), 
	"DESCRICAO" VARCHAR2(1000 BYTE), 
	"VALOR_PRODUTOS" VARCHAR2(250 BYTE),
	"VALOR_PRODUTOS_REAIS" NUMBER,
	"DEPOSITARIO" NUMBER(38,0), 
	"ENDERECO_LOGRADOURO" VARCHAR2(500 BYTE), 
	"ENDERECO_BAIRRO" VARCHAR2(100 BYTE), 
	"ENDERECO_DISTRITO" VARCHAR2(100 BYTE), 
	"ENDERECO_ESTADO" NUMBER(38,0), 
	"ENDERECO_MUNICIPIO" NUMBER(38,0), 
	"OPINIAO" VARCHAR2(250 BYTE), 
	"TID" VARCHAR2(36 BYTE), 
	 CONSTRAINT "PK_FIS_APREENSAO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_FIS_APREENS_FIS" FOREIGN KEY ("FISCALIZACAO")
	  REFERENCES "IDAF"."TAB_FISCALIZACAO" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_APREENS_PES" FOREIGN KEY ("DEPOSITARIO")
	  REFERENCES "IDAF"."TAB_PESSOA" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_APREENS_SER" FOREIGN KEY ("SERIE")
	  REFERENCES "IDAF"."LOV_FISCALIZACAO_SERIE" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_APREENS_EST" FOREIGN KEY ("ENDERECO_ESTADO")
	  REFERENCES "IDAF"."LOV_ESTADO" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_APREENS_MUN" FOREIGN KEY ("ENDERECO_MUNICIPIO")
	  REFERENCES "IDAF"."LOV_MUNICIPIO" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_APREENS_ARQ" FOREIGN KEY ("ARQUIVO")
	  REFERENCES "IDAF"."TAB_ARQUIVO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ID" IS 'Chave primaria. Utiliza a sequencia seq_tab_fisc_apreensao.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."FISCALIZACAO" IS 'Chave estrangeira para tab_fisc_infracao. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."IUF_DIGITAL" IS 'Informa se IUF é digital ou bloco. 1 - digital | 0 - bloco.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."IUF_NUMERO" IS 'Informa o número do IUF.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."IUF_DATA" IS 'Data do IUF.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ARQUIVO" IS 'Chave estrangeira para tab_arquivo. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."SERIE" IS 'Chave estrangeira para lov_fiscalizacao_serie. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."DESCRICAO" IS 'Descrição.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."VALOR_PRODUTOS" IS 'Valor dos produtos/bens apreeendidos, por extenso.';
   
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."VALOR_PRODUTOS_REAIS" IS 'Valor dos produtos/bens apreeendidos, em reais.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."DEPOSITARIO" IS 'Chave estrangeira para tab_pessoa. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ENDERECO_LOGRADOURO" IS 'Logradouro do depositario.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ENDERECO_BAIRRO" IS 'Bairro do depositario.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ENDERECO_DISTRITO" IS 'Distrito do depositario.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ENDERECO_ESTADO" IS 'Chave estrangeira para lov_estado. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."ENDERECO_MUNICIPIO" IS 'Chave estrangeira para lov_municipio. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."OPINIAO" IS 'Opinar pelo destino (permanencia no local, doação, uso pela instituição, entre outros) do material e/ou bens apreendido, levando-se em considerac?o os seguintes itens: localizac?o e sua dispers?o no local, potencial impacto que a retirada do material possa causar a area, valor economico, diametro medio das especies, entre outros.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_FISC_APREENSAO"  IS 'Tabela de apreensão da fiscalização.';
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_ARQ" ON "IDAF"."TAB_FISC_APREENSAO" ("ARQUIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_DEP" ON "IDAF"."TAB_FISC_APREENSAO" ("DEPOSITARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_EST" ON "IDAF"."TAB_FISC_APREENSAO" ("ENDERECO_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_FIS" ON "IDAF"."TAB_FISC_APREENSAO" ("FISCALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_MUN" ON "IDAF"."TAB_FISC_APREENSAO" ("ENDERECO_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_SER" ON "IDAF"."TAB_FISC_APREENSAO" ("SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APREENS_TID" ON "IDAF"."TAB_FISC_APREENSAO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
