
  CREATE TABLE "IDAF"."TAB_FISC_APREENSAO_PRODUTO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
  "APREENSAO" NUMBER(38,0) NOT NULL ENABLE,
	"PRODUTO" NUMBER(38,0) NOT NULL ENABLE, 
	"QUANTIDADE" NUMBER NOT NULL ENABLE, 
	"DESTINACAO" NUMBER(38,0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TAB_FISC_APREENSAO_PRODUTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
   CONSTRAINT "TAB_FISC_APREE_PROD_APR_FK" FOREIGN KEY ("APREENSAO")
	  REFERENCES "IDAF"."TAB_FISC_APREENSAO" ("ID") ENABLE, 
	 CONSTRAINT "TAB_FISC_APREE_PROD_DEST_FK" FOREIGN KEY ("DESTINACAO")
	  REFERENCES "IDAF"."CNF_FISC_INFR_DESTINACAO" ("ID") ENABLE, 
	 CONSTRAINT "TAB_FISC_APREE_PROD_PROD_FK" FOREIGN KEY ("PRODUTO")
	  REFERENCES "IDAF"."CNF_FISC_INFRACAO_PRODUTO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO_PRODUTO"."ID" IS 'Chave primária. Utiliza a sequência SEQ_TAB_FISC_APREENSAO_PRODUTO.';
   
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO_PRODUTO"."APREENSAO" IS 'Chave estrangeira para a tabela TAB_FISC_APREENSAO. Campo (ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO_PRODUTO"."PRODUTO" IS 'Chave estrangeira para a tabela CNF_FISC_INFRACAO_PRODUTO. Campo (ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO_PRODUTO"."QUANTIDADE" IS 'Quantidade do produto especificado.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO_PRODUTO"."DESTINACAO" IS 'Chave estrangeira para a tabela CNF_FISC_INFR_DESTINACAO. Campo (ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_APREENSAO_PRODUTO"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_FISC_APREENSAO_PRODUTO"  IS 'Tabela de Produtos Apreendidos do novo módulo de Fiscalização. Guarda os produtos e as respectivas destinações de uma apreensão.';
 
  CREATE INDEX "IDAF"."IDX_FIS_APREEN_PROD_APREEN" ON "IDAF"."TAB_FISC_APREENSAO_PRODUTO" ("APREENSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APR_PROD_TID" ON "IDAF"."TAB_FISC_APREENSAO_PRODUTO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_APR_PROD_PROD" ON "IDAF"."TAB_FISC_APREENSAO_PRODUTO" ("PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_FIS_APR_PROD_DEST" ON "IDAF"."TAB_FISC_APREENSAO_PRODUTO" ("DESTINACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;