
---grant update any table to [usuário do DB];

GRANT SELECT ON IDAFCREDENCIADO.tab_lote TO IDAF;
GRANT SELECT ON IDAFCREDENCIADO.tab_cfoc_produto TO IDAF;
GRANT SELECT ON IDAFCREDENCIADO.TAB_CFO TO IDAF;
GRANT SELECT ON IDAFCREDENCIADO.TAB_CFOC TO IDAF;

GRANT UPDATE ON IDAFCREDENCIADO.tab_lote TO IDAF;
GRANT UPDATE ON IDAFCREDENCIADO.tab_cfoc_produto TO IDAF;
GRANT UPDATE ON IDAFCREDENCIADO.TAB_CFO TO IDAF;
GRANT UPDATE ON IDAFCREDENCIADO.TAB_CFOC TO IDAF;

GRANT DELETE ON IDAFCREDENCIADO.tab_cfoc_produto TO IDAF;