  CREATE TABLE "IDAF"."TAB_FISC_PARAMETRIZACAO"
  (
    "ID"                NUMBER(38,0) NOT NULL ENABLE,
    "CODIGORECEITA"     NUMBER(38,0) NOT NULL ENABLE,
    "INICIOVIGENCIA"    DATE,
    "FIMVIGENCIA"       DATE,
    "VALORMINIMO_PF"    NUMBER(5,0) NOT NULL ENABLE,
    "VALORMINIMO_PJ"    NUMBER(5,0) NOT NULL ENABLE,
    "MULTA_PERC"        NUMBER(3,0) NOT NULL ENABLE,
    "JUROS_PERC"        NUMBER(3,0) NOT NULL ENABLE,
    "DESCONTO_PERC"     NUMBER(3,0) NOT NULL ENABLE,
    "DESCONTO_UND"      NUMBER(3,0) NOT NULL ENABLE,
    "DESCONTO_DECOR"    NUMBER(1,0) NOT NULL ENABLE,    
    "TID"              VARCHAR2(36 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_FIS_PAR" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ENABLE,
    CONSTRAINT "FK_FIS_PAR_REC" FOREIGN KEY ("CODIGORECEITA") REFERENCES "IDAF"."LOV_FISC_INFRACAO_CODIGO_RECE" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "IDAF_TBS" ;
 
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."ID" IS 'Chave primaria. Utiliza a sequencia seq_fisc_parametrizacao.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."CODIGORECEITA" IS 'Chave estrangeira para lov_fisc_infracao_codigo_rece. Campo(ID).';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."INICIOVIGENCIA" IS 'Data inicio de vigência da parametrização.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."FIMVIGENCIA" IS 'Data fim de vigência da parametrização.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."VALORMINIMO_PF" IS 'Informa o valor mínimo para parcela de pessoa física.';

  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."VALORMINIMO_PJ" IS 'Informa o valor mínimo para parcela de pessoa jurídica.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."MULTA_PERC" IS 'Informa o percentual utilizado para realizar o cálculo de multa.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."JUROS_PERC" IS 'Informa o percentual utilizado para realizar o cálculo de juros.';
    
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."DESCONTO_PERC" IS 'Informa o percentual utilizado para realizar o cálculo de desconto.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."DESCONTO_UND" IS 'Informa a unidade de decorrência utilizada para cálculo de desconto.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."DESCONTO_DECOR" IS 'Informa a forma de decorrência utilizada para cálculo de desconto. 1 - Dia, 2 - Mês, 3 - Ano.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAMETRIZACAO"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
  
  COMMENT ON TABLE "IDAF"."TAB_FISC_PARAMETRIZACAO"  IS 'Tabela de parametrização financeira.';
 
  CREATE INDEX "IDAF"."IDX_FIS_PAR_REC" ON "IDAF"."TAB_FISC_PARAMETRIZACAO" ("CODIGORECEITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  
  CREATE INDEX "IDAF"."IDX_FIS_PAR_TID" ON "IDAF"."TAB_FISC_PARAMETRIZACAO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
