
  CREATE TABLE "IDAF"."HST_FISC_PARAMETRIZACAO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
  "PARAMETRIZACAO_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CODIGORECEITA_ID" NUMBER(38,0),
  "CODIGORECEITA_TEXTO"	VARCHAR2(50 BYTE),  
  "INICIOVIGENCIA"	DATE,
  "FIMVIGENCIA"	DATE,
  "VALORMINIMO_PF"   NUMBER(5,0),
  "VALORMINIMO_PJ"   NUMBER(5,0),
	"MULTA_PERC" NUMBER(3,0), 
	"JUROS_PERC" NUMBER(3,0), 
	"DESCONTO_PERC" NUMBER(3,0), 
	"DESCONTO_UND" NUMBER(3,0), 
	"DESCONTO_DECOR" NUMBER(1,0),   
  "TID"	VARCHAR2(36 BYTE)	NOT NULL,  
  "EXECUTOR_ID" NUMBER(38,0), 
	"EXECUTOR_TID" VARCHAR2(36 BYTE), 
	"EXECUTOR_NOME" VARCHAR2(80 BYTE), 
	"EXECUTOR_LOGIN" VARCHAR2(30 BYTE), 
	"EXECUTOR_TIPO_ID" NUMBER(38,0), 
	"EXECUTOR_TIPO_TEXTO" VARCHAR2(30 BYTE), 
	"ACAO_EXECUTADA" NUMBER(38,0) NOT NULL ENABLE, 
	"DATA_EXECUCAO" TIMESTAMP (6) NOT NULL ENABLE,
  CONSTRAINT "PK_HST_FISC_PARAMETRIZACAO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."ID"						            IS 'Chave primaria. Utiliza a sequencia seq_hst_fisc_parametrizacao.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."PARAMETRIZACAO_ID"        IS 'Campo Id da tabela tab_fisc_parametrizacao.';	
	COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."CODIGORECEITA_ID"         IS 'Chave estrangeira para lov_fisc_infracao_codigo_rece. Campo(ID).';	
	COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."CODIGORECEITA_TEXTO"      IS 'Código de receita utilizado. Campo (TEXTO) da tabela lov_fisc_infracao_codigo_rece.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."INICIOVIGENCIA"           IS 'Data inicio de vigência.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."FIMVIGENCIA"              IS 'Data fim de vigência.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."VALORMINIMO_PF"           IS 'Informa o valor mínimo para parcela de pessoa física.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."VALORMINIMO_PJ"           IS 'Informa o valor mínimo para parcela de pessoa jurídica.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."MULTA_PERC"               IS 'Informa o percentual utilizado para realizar o cálculo de multa.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."JUROS_PERC"               IS 'Informa o percentual utilizado para realizar o cálculo de juros.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."DESCONTO_PERC"            IS 'Informa o percentual utilizado para realizar o cálculo de desconto.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."DESCONTO_UND"             IS 'Informa a unidade de decorrência utilizada para cálculo de desconto.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."DESCONTO_DECOR"           IS 'Informa a forma de decorrência utilizada para cálculo de desconto. 1 - Dia, 2 - Mês, 3 - Ano.';
	COMMENT ON COLUMN "IDAF"."HST_FISC_PARAMETRIZACAO"."TID"                      IS 'Id transacional. Esse valor garante a ligacao entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_PARAMETRIZACAO"  IS 'Tabela com o historico da tabela tab_fisc_parametrizacao da Fiscalizacao.';
 
  CREATE INDEX "IDAF"."IDX_HST_FISC_PAR_RECE" ON "IDAF"."HST_FISC_PARAMETRIZACAO" ("CODIGORECEITA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
  CREATE INDEX "IDAF"."IDX_HST_FISC_PAR_TID" ON "IDAF"."HST_FISC_PARAMETRIZACAO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
