  CREATE TABLE IDAF.LOV_CRT_EXP_FLORES_TIPO 
   (	ID NUMBER(38,0) NOT NULL ENABLE, 
	TEXTO VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT PK_LOV_CRT_EXP_FLORES_TIPO PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE IDAF_TBS  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE IDAF_TBS ;
 

   COMMENT ON COLUMN IDAF.LOV_CRT_EXP_FLORES_TIPO.ID IS 'Chave primaria de identificacao da tabela.';
 
   COMMENT ON COLUMN IDAF.LOV_CRT_EXP_FLORES_TIPO.TEXTO IS 'Texto de exploracao.';
 
   COMMENT ON TABLE IDAF.LOV_CRT_EXP_FLORES_TIPO  IS 'lista dos tipos de exploracao da caracterizacao';
 
insert into lov_crt_exp_flores_tipo (id, texto) values (1, 'AUS (Uso Alternativo do Solo)');
insert into lov_crt_exp_flores_tipo (id, texto) values (2, 'CAI (Corte de Árvore Isolada)');
insert into lov_crt_exp_flores_tipo (id, texto) values (3, 'EFP (Exploração de Floresta Plantada)');