  ALTER TABLE TAB_PROTOCOLO ADD ORGAO_DESTINO VARCHAR2(100 BYTE);
  ALTER TABLE TAB_PROTOCOLO ADD CARGO_DESTINATARIO VARCHAR2(100 BYTE);
  ALTER TABLE TAB_PROTOCOLO ADD NOME_DESTINATARIO VARCHAR2(100 BYTE);
  ALTER TABLE TAB_PROTOCOLO ADD ENDERECO_DESTINATARIO VARCHAR2(100 BYTE);
  
  ALTER TABLE HST_PROTOCOLO ADD ORGAO_DESTINO VARCHAR2(100 BYTE);
  ALTER TABLE HST_PROTOCOLO ADD CARGO_DESTINATARIO VARCHAR2(100 BYTE);
  ALTER TABLE HST_PROTOCOLO ADD NOME_DESTINATARIO VARCHAR2(100 BYTE);
  ALTER TABLE HST_PROTOCOLO ADD ENDERECO_DESTINATARIO VARCHAR2(100 BYTE);
    
  COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO"."ORGAO_DESTINO" IS 'Orgao ou empresa destino com digitação livre.'; 
  COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO"."CARGO_DESTINATARIO" IS 'Cargo ou funcao do destinatario com digitação livre.';  
  COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO"."NOME_DESTINATARIO" IS 'Nome do destinatario com digitação livre.';  
  COMMENT ON COLUMN "IDAF"."TAB_PROTOCOLO"."ENDERECO_DESTINATARIO" IS 'Endereco do destinatario com digitação livre.';  

  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."ORGAO_DESTINO" IS 'Orgao ou empresa destino com digitação livre.'; 
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."CARGO_DESTINATARIO" IS 'Cargo ou funcao do destinatario com digitação livre.';  
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."NOME_DESTINATARIO" IS 'Nome do destinatario com digitação livre.';  
  COMMENT ON COLUMN "IDAF"."HST_PROTOCOLO"."ENDERECO_DESTINATARIO" IS 'Endereco do destinatario com digitação livre.';  
