ALTER TABLE LOV_PROTOCOLO_TIPO ADD DESTINATARIO_LIVRE NUMBER(1,0);
COMMENT ON COLUMN LOV_PROTOCOLO_TIPO.DESTINATARIO_LIVRE IS  '0 - não possui, 1 - obrigatório, 2 - opcional.';	
UPDATE LOV_PROTOCOLO_TIPO SET DESTINATARIO_LIVRE = 0;
UPDATE LOV_PROTOCOLO_TIPO SET PROCESSO = 0, DOCUMENTO = 0, INTERESSADO = 0, INTERESSADO_LIVRE = 0, NOME = 0, QTD_DOCUMENTO = 0, ASSUNTO = 1, DESCRICAO = 0, DESTINATARIO_LIVRE = 1 WHERE ID = 15;