
SELECT * FROM IDAFCONSULTA.LST_PROTOCOLO;

ALTER TABLE IDAFCONSULTA.LST_PROTOCOLO 
ADD ( INTERESSADO_LIVRE VARCHAR2(100),
      INTERESSADO_LIVRE_TELEFONE VARCHAR2(20),
      FOLHAS NUMBER(4,0));
      
ALTER TABLE IDAFCONSULTA.LST_PROTOCOLO 
MODIFY (NOME VARCHAR2(100));   

COMMENT ON COLUMN IDAFCONSULTA.LST_PROTOCOLO.INTERESSADO_LIVRE IS 'Interessado do documento de digitação livre';	
COMMENT ON COLUMN IDAFCONSULTA.LST_PROTOCOLO.INTERESSADO_LIVRE_TELEFONE IS 'Telefone do Interessado do documento de digitação livre';	
COMMENT ON COLUMN IDAFCONSULTA.LST_PROTOCOLO.FOLHAS IS 'Quantidade de folhas do documento';