CREATE TABLE "IDAF"."CNF_IMPLANTACAO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CAMPO" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"VALOR" CLOB, 
	 CONSTRAINT "PK_CNF_IMPLANTACAO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "UK_CNF_IMPLANTACAO" UNIQUE ("CAMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" 
 LOB ("VALOR") STORE AS (
  TABLESPACE "IDAF_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ; 

   COMMENT ON COLUMN "IDAF"."CNF_IMPLANTACAO"."ID" IS 'Chave primária de identificação da tabela.';
 
   COMMENT ON COLUMN "IDAF"."CNF_IMPLANTACAO"."CAMPO" IS 'Nome do campo que sera guardada o valor de configurac?o.';
 
   COMMENT ON COLUMN "IDAF"."CNF_IMPLANTACAO"."VALOR" IS 'Valord do campo de configurac?o.';
 
   COMMENT ON TABLE "IDAF"."CNF_IMPLANTACAO"  IS 'Tabela de configurac?es de valores usados para implantacao';

  INSERT INTO CNF_IMPLANTACAO (ID, CAMPO, VALOR) 
  SELECT (SELECT COALESCE(MAX(ID),0) + 1  FROM CNF_IMPLANTACAO), 'ultimoscript', '0000.000.000' FROM DUAL
  WHERE NOT EXISTS
  (SELECT 1 FROM CNF_IMPLANTACAO WHERE CAMPO like 'ultimoscript');
  
  UPDATE CNF_IMPLANTACAO SET VALOR = '2018.005.000' WHERE CAMPO like 'ultimoscript';