SELECT * FROM LOV_PROTOCOLO_TIPO;
SELECT * FROM TAB_PROTOCOLO;
SELECT * FROM HST_PROTOCOLO;
SELECT * FROM IDAFCONSULTA.LST_PROTOCOLO;

ALTER TABLE TAB_PROTOCOLO 
ADD ( INTERESSADO_LIVRE VARCHAR2(100),
      INTERESSADO_LIVRE_TELEFONE VARCHAR2(20),
      FOLHAS NUMBER(4,0));
      
ALTER TABLE HST_PROTOCOLO 
ADD ( INTERESSADO_LIVRE VARCHAR2(100),
      INTERESSADO_LIVRE_TELEFONE VARCHAR2(20),
      FOLHAS NUMBER(4,0));
      
ALTER TABLE TAB_PROTOCOLO 
MODIFY (NOME VARCHAR2(100));

COMMENT ON COLUMN TAB_PROTOCOLO.INTERESSADO_LIVRE IS 'Interessado do documento de digitação livre';	
COMMENT ON COLUMN TAB_PROTOCOLO.INTERESSADO_LIVRE_TELEFONE IS 'Telefone do Interessado do documento de digitação livre';	
COMMENT ON COLUMN TAB_PROTOCOLO.FOLHAS IS 'Quantidade de folhas do documento';	

COMMENT ON COLUMN HST_PROTOCOLO.INTERESSADO_LIVRE IS 'Interessado do documento de digitação livre';	
COMMENT ON COLUMN HST_PROTOCOLO.INTERESSADO_LIVRE_TELEFONE IS 'Telefone do Interessado do documento de digitação livre';	
COMMENT ON COLUMN HST_PROTOCOLO.FOLHAS IS 'Quantidade de folhas do documento';	

UPDATE LOV_PROTOCOLO_TIPO SET PROCESSO = 0 WHERE ID = 13;	
UPDATE LOV_PROTOCOLO_TIPO SET INTERESSADO = 0 WHERE ID = 13;

UPDATE LOV_PROTOCOLO_TIPO SET INTERESSADO_LIVRE = 0;
UPDATE LOV_PROTOCOLO_TIPO SET INTERESSADO_LIVRE = 2 WHERE ID = 13;	

