  CREATE SEQUENCE seq_integracao_sinaflor INCREMENT BY 1 START WITH 1 NOMAXVALUE MINVALUE 1 NOCACHE;

  CREATE TABLE "IDAF"."TAB_INTEGRACAO_SINAFLOR"
  (
    "ID"                NUMBER(38,0) NOT NULL ENABLE,
    "DESCRICAO"         VARCHAR(4000) NOT NULL ENABLE,
    "SITUACAO"          VARCHAR(255) NOT NULL ENABLE,
    "SERVICO"           VARCHAR(255) NOT NULL ENABLE,
    "DATA"              TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "PK_INTEGRACAO_SINAFLOR" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "IDAF_TBS" ;
 
  COMMENT ON COLUMN "IDAF"."TAB_INTEGRACAO_SINAFLOR"."ID" IS 'Chave primaria. Utiliza a sequencia seq_integracao_sinaflor.';
  
  COMMENT ON COLUMN "IDAF"."TAB_INTEGRACAO_SINAFLOR"."DESCRICAO" IS 'Informa o resultado da integracao com o SINAFLOR.';
  
  COMMENT ON COLUMN "IDAF"."TAB_INTEGRACAO_SINAFLOR"."SITUACAO" IS 'Informa a situacao da integracao.';
  
  COMMENT ON COLUMN "IDAF"."TAB_INTEGRACAO_SINAFLOR"."SERVICO" IS 'Informa o servico que realizara integracao.';
  
  COMMENT ON COLUMN "IDAF"."TAB_INTEGRACAO_SINAFLOR"."DATA" IS 'Informa a data da integracao no SINAFLOR.';
  
  COMMENT ON TABLE "IDAF"."TAB_INTEGRACAO_SINAFLOR"  IS 'Tabela de integracao com SINAFLOR.';