CREATE TABLE "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"PTV" NUMBER(38,0) NOT NULL ENABLE, 
	"NF_CAIXA" NUMBER(38,0) NOT NULL ENABLE, 
	"SALDO_ATUAL" NUMBER(38,0) NOT NULL ENABLE, 
	"NUMERO_CAIXAS" NUMBER(38,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TAB_PTV_NF_CAIXA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_PTV_NF_CAIXA_PTV" FOREIGN KEY ("PTV")
	  REFERENCES "IDAFCREDENCIADO"."TAB_PTV" ("ID") ENABLE, 
	 CONSTRAINT "FK_NF_CAIXA" FOREIGN KEY ("NF_CAIXA")
	  REFERENCES "IDAF"."TAB_NF_CAIXA" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA"."ID" IS 'Chave primária de identificação da tabela.';
 
   COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA"."TID" IS 'Id transacional.Esse valor garante a ligação entre as tabelas relacionadas com essa transaction.';
 
   COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA"."PTV" IS 'Chave estrangeira para tab_ptv. Campo(ID).';
 
   COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA"."NF_CAIXA" IS 'Chave estrangeira para tab_nf_caixa. Campo(ID).';
 
   COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA"."SALDO_ATUAL" IS 'Saldo de caixas antes de serem utilizadas.';
 
   COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_PTV_NF_CAIXA"."NUMERO_CAIXAS" IS 'Saldo de caixas utilizado.';
 