UPDATE LOV_SOLICITACAO_PTV_SITUACAO SET TEXTO = 'Rejeitado' WHERE ID = 4;

UPDATE CNF_IMPLANTACAO SET VALOR = '2018.007.001' WHERE CAMPO like 'ultimoscript';


--SELECT VALOR FROM CNF_IMPLANTACAO WHERE CAMPO like 'ultimoscript';