
  CREATE TABLE "IDAFGEO"."LOV_TIPO_EXPLORACAO" 
   (	"CHAVE" VARCHAR2(10 BYTE), 
	"TEXTO" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_LOV_TIPO_EXPLORACAO" PRIMARY KEY ("CHAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAFGEO_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAFGEO_TBS" ;
 

   COMMENT ON COLUMN "IDAFGEO"."LOV_TIPO_EXPLORACAO"."CHAVE" IS 'Chave primaria para LOV_TIPO_EXPLORACAO';
 
   COMMENT ON COLUMN "IDAFGEO"."LOV_TIPO_EXPLORACAO"."TEXTO" IS 'Valor da coluna';
 
   COMMENT ON TABLE "IDAFGEO"."LOV_TIPO_EXPLORACAO"  IS 'Lista de valores para as tabelas do desenhador';
 
