------ Criação de sequence e tabela de histórico de nota fiscal de caixa do PTV (hst_ptv_nf_caixa) (credenciado)

CREATE SEQUENCE  "IDAFCREDENCIADO"."SEQ_HST_PTV_NF_CAIXA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 57542 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA" 
( "ID" NUMBER(38,0) NOT NULL ENABLE,
  "TID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
  "ID_HST" NUMBER(38,0) NOT NULL ENABLE,
  "PTV_NF_CAIXA_ID" NUMBER(38,0) NOT NULL ENABLE,
  "PTV_ID" NUMBER(38,0) NOT NULL ENABLE,
  "NF_CAIXA_ID" NUMBER(38,0) NOT NULL ENABLE,
  "NF_CAIXA_TID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
  "SALDO_ATUAL" NUMBER(38,0) NOT NULL ENABLE, 
  "NUMERO_CAIXAS" NUMBER(38,0) NOT NULL ENABLE,
  
  CONSTRAINT "PK_HST_PTV_NF_CAIXA" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ENABLE, 
  
  CONSTRAINT "FK_HST_PTV_NFCAIXA" FOREIGN KEY ("ID_HST") REFERENCES "IDAFCREDENCIADO"."HST_PTV" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ;

COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."ID" IS 'Chave primária de identificação da tabela.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."TID" IS 'Id transacional.Esse valor garante a ligação entre as tabelas relacionadas com essa transaction.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."ID_HST" IS 'Chave estrangeira da tabela hst_ptv.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."PTV_NF_CAIXA_ID" IS 'Chave estrangeira para tab_ptv_nf_caixa. Campo(ID)';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."PTV_ID" IS 'Chave estrangeira para tab_ptv. Campo(ID)';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."NF_CAIXA_ID" IS 'Chave estrangeira para tab_nf_caixa. Campo(ID).';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."NF_CAIXA_TID" IS 'Referência ao campo (TID) da tabela tab_nf_caixa.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."SALDO_ATUAL" IS 'Saldo de caixas antes de serem utilizadas.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"."NUMERO_CAIXAS" IS 'Saldo de caixas utilizado.';

COMMENT ON TABLE "IDAFCREDENCIADO"."HST_PTV_NF_CAIXA"  IS 'Tabela de histórico de Nota Fiscal de caixas do PTV.';