//RQF 01 e 04: Criação de tipo de documento
--Documento Avulso
INSERT INTO "IDAF"."LOV_PROTOCOLO_TIPO" (ID, TEXTO, PROCESSO, DOCUMENTO, CHECAGEM_PENDENCIA, 		CHECAGEM_ROTEIRO, REQUERIMENTO, TIPO, FISCALIZACAO, INTERESSADO) 
VALUES ('13', 'Documento Avulso', '2', '0', '0', '0', '0', '2', '0', '2');

--CI - Comunicação Interna
INSERT INTO "IDAF"."LOV_PROTOCOLO_TIPO" (ID, TEXTO, PROCESSO, DOCUMENTO, CHECAGEM_PENDENCIA, 		CHECAGEM_ROTEIRO, REQUERIMENTO, TIPO, FISCALIZACAO, INTERESSADO) 
VALUES ('14', 'CI - Comunicação Interna', '2', '0', '0', '0', '0', '2', '0', '2');

--Ofício (Administrativo) 
INSERT INTO "IDAF"."LOV_PROTOCOLO_TIPO" (ID, TEXTO, PROCESSO, DOCUMENTO, CHECAGEM_PENDENCIA, 		
CHECAGEM_ROTEIRO, REQUERIMENTO, TIPO, FISCALIZACAO, INTERESSADO) 
VALUES ('15', 'Ofício (Administrativo)', '2', '0', '0', '0', '0', '2', '0', '2');