namespace Tecnomapas.Blocos.Entities.Interno.Extensoes.Especificidades.ModuloEspecificidade
{
	public enum eEspecificidade
	{
		//Nome exato da tela / Codigo do Modelo
		Nulo = 0,
		OficioNotificacao = 1,
		LaudoConstatacao = 2,
		CertificadoRegistro = 3,
		LaudoVistoriaFlorestal = 4,
		AutorizacaoExploracaoFlorestal = 5,
		LaudoVistoriaFundiaria = 6,
		EscrituraPublicaDoacao = 7,
		EscrituraPublicaCompraVenda = 8,
		CadComercProdutosAgrotoxicos = 9,
		CadAplicProdutosAgrotoxicos = 10,
		CertidaoAnuencia = 11,
		LicencaPorteUsoMotosserra = 20,
		TermoAprovacaoMedicao = 21,
		AutorizacaoQueimaControlada = 22,
		CertificadoCadastroProdutoVegetal = 23,
		LicencaOperacao = 15,
		LicencaInstalacao = 14,
		LicencaPrevia = 13,
		LicencaAmbientalRegularizacao = 16,
		LicencaAmbientalUnica = 17,
		LicencaSimplificada = 12,
		LaudoVistoriaLicenciamento = 26,
		LaudoFundiarioSimplificado = 27,
		CertificadoRegistroAtividadeFlorestal = 19,
		LicencaOperacaoFomento = 37,
		OutrosReciboEntregaCopia = 38,
		OutrosConclusaoTransferenciaDominio = 39,
		NotificacaoEmbargo = 40,
		CertidaoCartaAnuencia = 41,
		TermoCPFARL = 42,
		LaudoAuditoriaFomentoFlorestal = 30,
		LaudoVistoriaFomentoFlorestal = 18,
		TermoCPFARLR = 43,
		OutrosLegitimacaoTerraDevoluta = 28,
		OutrosInformacaoCorte = 46,
		OutrosInformacaoCorteDeclaratorio = 61,
		CertidaoDebito = 47,
		OficioUsucapiao = 48,
		CadastroAmbientalRuralTitulo = 49,
		TermoCompromissoAmbiental = 50,
		AberturaLivroUnidadeProducao = 51,
		AberturaLivroUnidadeConsolidacao = 52,
		CertificadoCadastroProdutoAgrotoxico = 53,
		TermoCPFARLC = 44,
		TermoCPFARLCR = 45,
		CertidaoDispensaLicenciamentoAmbiental = 54,
		LaudoVistoriaQueimaControlada = 60
	}
}