--CREDENCIADO
GRANT select ON IDAFCREDENCIADO.HST_REQUERIMENTO TO IDAF;
GRANT SELECT ON IDAFCREDENCIADO.tab_usuario TO idaf;

-----------------------------------------------------

--INSTITUCIONAL
ALTER TABLE IDAF.HST_TITULO
ADD EXECUTOR_IP VARCHAR2(40)
;
COMMENT ON COLUMN "IDAF"."HST_TITULO"."EXECUTOR_IP" IS 'IP de onde a ação foi executada.'

