
  CREATE TABLE "IDAF"."HST_FISC_COBRANCA" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
  "COBRANCA_ID"       NUMBER(38,0) NOT NULL ENABLE, 
  "FISCALIZACAO"      NUMBER(38,0) NOT NULL ENABLE,
  "AUTUADO_ID"        NUMBER(38,0) NOT NULL ENABLE,
  "AUTUADO_NOME"      VARCHAR2(80 BYTE),
  "CODIGORECEITA_ID"  NUMBER(38,0),
  "CODIGORECEITA_TEXTO"	VARCHAR2(50 BYTE),  
  "SERIE_ID"          NUMBER(38,0),
  "SERIE_TEXTO"	      VARCHAR2(50 BYTE),  
  "IUF_NUMERO"        NUMBER(38,0),
  "IUF_DATA"        	DATE,
  "PROTOC_NUM"        VARCHAR2(36 BYTE),
  "AUTOS"             NUMBER(38,0),    
  "NOT_IUF_DATA"   	  DATE,
  "NOT_JIAPI_DATA"   	DATE,
  "NOT_CORE_DATA"   	DATE,
  "TID"	VARCHAR2(36 BYTE)	NOT NULL,  
  "EXECUTOR_ID" NUMBER(38,0), 
	"EXECUTOR_TID" VARCHAR2(36 BYTE), 
	"EXECUTOR_NOME" VARCHAR2(80 BYTE), 
	"EXECUTOR_LOGIN" VARCHAR2(30 BYTE), 
	"EXECUTOR_TIPO_ID" NUMBER(38,0), 
	"EXECUTOR_TIPO_TEXTO" VARCHAR2(30 BYTE), 
	"ACAO_EXECUTADA" NUMBER(38,0) NOT NULL ENABLE, 
	"DATA_EXECUCAO" TIMESTAMP (6) NOT NULL ENABLE,
  CONSTRAINT "PK_HST_FISC_COBRANCA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
	COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."ID"	IS 'Chave primaria. Utiliza a sequencia seq_hst_fisc_cobranca.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."COBRANCA_ID" IS 'Campo Id da tabela tab_fisc_cobranca.';	
	COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."FISCALIZACAO" IS 'Informa o número da fiscalizacao (poderá existir na tabela tab_fiscalizacao. Campo (ID))';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."AUTUADO_ID" IS 'Chave estrangeira com a tabela tab_pessoa. Campo (ID)';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."AUTUADO_NOME" IS 'Nome informado na tabela tab_pessoa. Campo (Nome).';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."CODIGORECEITA_ID" IS 'Chave estrangeira para lov_fisc_infracao_codigo_rece. Campo(ID).';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."CODIGORECEITA_TEXTO" IS 'Texto informado na tabela lov_fisc_infracao_codigo_rece. Campo (Texto).';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."SERIE_ID" IS 'Chave estrangeira para lov_fiscalizacao_serie. Campo(ID).';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."SERIE_TEXTO" IS 'Texto informado na tabela lov_fiscalizacao_serie. Campo (Texto).';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."IUF_NUMERO" IS 'Informa o número do IUF.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."IUF_DATA" IS 'Data do IUF..';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."PROTOC_NUM" IS 'Informa o número de protocolo.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."AUTOS" IS 'Numero de Autos/Temos de N? AI, N? TEI e N? TAD. Utiliza a sequencia seq_fiscalizacao_autos.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."NOT_IUF_DATA" IS 'Data da notificação IUF.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."NOT_JIAPI_DATA" IS 'Data da notificação JIAPI.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."NOT_CORE_DATA" IS 'Data da notificação CORE.';
  COMMENT ON COLUMN "IDAF"."HST_FISC_COBRANCA"."TID" IS 'Id transacional. Esse valor garante a ligacao entre todas as tabelas relacionadas com essa transaction.';
 
	COMMENT ON TABLE "IDAF"."HST_FISC_COBRANCA"  IS 'Tabela com o historico da tabela tab_fisc_cobranca da Fiscalizacao.';
 
  CREATE INDEX "IDAF"."IDX_HST_FISC_COB_COB" ON "IDAF"."HST_FISC_COBRANCA" ("COBRANCA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_HST_FISC_COB_FIS" ON "IDAF"."HST_FISC_COBRANCA" ("FISCALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_HST_FISC_COB_AUT" ON "IDAF"."HST_FISC_COBRANCA" ("AUTUADO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
  CREATE INDEX "IDAF"."IDX_HST_FISC_COB_RECE" ON "IDAF"."HST_FISC_COBRANCA" ("CODIGORECEITA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_HST_FISC_COB_SERIE" ON "IDAF"."HST_FISC_COBRANCA" ("SERIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
  CREATE INDEX "IDAF"."IDX_HST_FISC_COB_TID" ON "IDAF"."HST_FISC_COBRANCA" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
