namespace Tecnomapas.Blocos.Entities.Interno.Extensoes.Caracterizacoes.ModuloCadastroAmbientalRural
{
	public enum eCadastroAmbientalRuralArea
	{
		ATP_CROQUI = 1,
		AREA_DOCUMENTO,
		AREA_CCRI,
		AREA_USO_ALTERNATIVO,
		AREA_USO_RESTRITO_DECLIVIDADE,
		APP_TOTAL_CROQUI,
		APP_PRESERVADA,
		APP_RECUPERACAO,
		APP_USO,
		APP_RECUPERAR_CALCULADO,
		APP_RECUPERAR_EFETIVA,
		APP_USO_CONSOLIDADO,
		APP_NAO_CARACTERIZADA,
		ARL_CROQUI,
		ARL_DOCUMENTO,
		ARL_APP,
		ARL_PRESERVADA,
		ARL_RECUPERACAO,
		ARL_RECUPERAR,
		ARL_NAO_CARACTERIZADA,

		//Areas de processamento
		AA_USO,
		CALC_GEO_ATP,
		CALC_APP_AVN,
		CALC_APP_AA_REC,
		//CALC_ATP_MODULO,

		//COMPENSAÇÃO
		ARL_EMPREENDIMENTO,
		ARL_COMPENSADA,
		ARL_CEDENTE_PRESERVADA,
		ARL_CEDENTE_EM_RECUPERACAO,
		ARL_CEDENTE_RECUPERAR,
		ARL_CEDENTE_NAO_CARACTERIZADA,
		ARL_RECEPTORA_PRESERVADA,
		ARL_RECEPTORA_EM_RECUPERACAO,
		ARL_RECEPTORA_RECUPERAR,
		ARL_RECEPTORA_NAO_CARACTERIZADA,
		TOTAL_ARL_CEDENTE,
		TOTAL_ARL_RECEPTORA

	}
}