  CREATE TABLE "IDAF"."TAB_FISC_NOTIFICACAO"
  (
    "ID"               NUMBER(38,0) NOT NULL ENABLE,
    "FISCALIZACAO"     NUMBER(38,0) NOT NULL ENABLE,
    "FORMA_IUF"        NUMBER(1,0) NOT NULL ENABLE,
    "FORMA_JIAPI"      NUMBER(1,0) NOT NULL ENABLE,
    "FORMA_CORE"       NUMBER(1,0) NOT NULL ENABLE,
    "FORMA_IUF_DATA"   DATE,
    "FORMA_JIAPI_DATA" DATE,
    "FORMA_CORE_DATA"  DATE,
    "TID"              VARCHAR2(36 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_FIS_NOT" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ENABLE,
    CONSTRAINT "FK_FIS_NOT_FIS" FOREIGN KEY ("FISCALIZACAO") REFERENCES "IDAF"."TAB_FISCALIZACAO" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "IDAF_TBS" ;
 
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."ID" IS 'Chave primaria. Utiliza a sequencia seq_tab_fisc_multa.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FISCALIZACAO" IS 'Chave estrangeira para tab_fiscalizacao. Campo(ID).';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FORMA_IUF" IS 'Informa a forma de notificação IUF. 1 - pessoal | 2 - ar aviso de recebimento | 3 - por edital.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FORMA_JIAPI" IS 'Informa a forma de notificação JIAPI. 1 - pessoal | 2 - ar aviso de recebimento | 3 - por edital.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FORMA_CORE" IS 'Informa a forma de notificação CORE. 1 - pessoal | 2 - ar aviso de recebimento | 3 - por edital.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FORMA_IUF_DATA" IS 'Data da notificação IUF.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FORMA_JIAPI_DATA" IS 'Data da notificação JIAPI.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."FORMA_CORE_DATA" IS 'Data da notificação CORE.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_NOTIFICACAO"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
  
  COMMENT ON TABLE "IDAF"."TAB_FISC_NOTIFICACAO"  IS 'Tabela da notificação de fiscalização.';
 
  CREATE INDEX "IDAF"."IDX_FIS_NOT_FIS" ON "IDAF"."TAB_FISC_NOTIFICACAO" ("FISCALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  
  CREATE INDEX "IDAF"."IDX_FIS_NOT_TID" ON "IDAF"."TAB_FISC_NOTIFICACAO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
