
  CREATE TABLE "IDAF"."CNF_FISC_INFRACAO_PRODUTO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITEM" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"UNIDADE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ATIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CNF_FISC_INFRACAO_PRODUTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFRACAO_PRODUTO"."ID" IS 'Chave primária.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFRACAO_PRODUTO"."ITEM" IS 'Identificação do produto.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFRACAO_PRODUTO"."UNIDADE" IS 'Unidade relacionada com o produto.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFRACAO_PRODUTO"."ATIVO" IS 'Ativo: 0 - não | 1 - sim.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFRACAO_PRODUTO"."TID" IS 'Id transacional. Esse valor garante a ligac?o entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."CNF_FISC_INFRACAO_PRODUTO"  IS 'Tabela de produtos apreendidos a ser usada na configuração da fiscalização.';
 
