
  CREATE TABLE "IDAF"."CNF_FISC_INFR_DESTINACAO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DESTINO" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ATIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CNF_FISC_INFR_DESTINACAO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFR_DESTINACAO"."ID" IS 'Chave primária.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFR_DESTINACAO"."DESTINO" IS 'Identificação do destino.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFR_DESTINACAO"."ATIVO" IS 'Ativo: 0 - não | 1 - sim.';
 
   COMMENT ON COLUMN "IDAF"."CNF_FISC_INFR_DESTINACAO"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."CNF_FISC_INFR_DESTINACAO"  IS 'Tabela de destinação de produtos apreendidos, a ser usada na configuração da fiscalização.';
 
