
  CREATE TABLE "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PRODUTO_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITEM" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"UNIDADE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ATIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"EXECUTOR_ID" NUMBER(38,0), 
	"EXECUTOR_TID" VARCHAR2(36 BYTE), 
	"EXECUTOR_NOME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"EXECUTOR_LOGIN" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"EXECUTOR_TIPO_ID" NUMBER(38,0), 
	"EXECUTOR_TIPO_TEXTO" VARCHAR2(30 BYTE), 
	"ACAO_EXECUTADA" NUMBER(38,0) NOT NULL ENABLE, 
	"DATA_EXECUCAO" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_HST_CNF_FISC_INFRACAO_PROD" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_CNF_FISC_INFR_PROD_ACAO" FOREIGN KEY ("ACAO_EXECUTADA")
	  REFERENCES "IDAF"."LOV_HISTORICO_ARTEFATOS_ACOES" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON TABLE "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO"  IS 'Tabela do historico da Configuracao de Fiscalizacao - Produtos Apreendidos.';
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_P_EXEC_ACAO1" ON "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" ("ACAO_EXECUTADA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_P_EXEC_DATA1" ON "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" ("DATA_EXECUCAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_P_EXEC_TID1" ON "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" ("EXECUTOR_TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_P_EXE_TIP_I" ON "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" ("EXECUTOR_TIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_P_TID1" ON "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_P_TIPO_ID1" ON "IDAF"."HST_CNF_FISC_INFRACAO_PRODUTO" ("PRODUTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
