
  CREATE TABLE "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DESTINACAO_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DESTINO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ATIVO" NUMBER(1,0) NOT NULL ENABLE, 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"EXECUTOR_ID" NUMBER(38,0), 
	"EXECUTOR_TID" VARCHAR2(36 BYTE), 
	"EXECUTOR_NOME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"EXECUTOR_LOGIN" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"EXECUTOR_TIPO_ID" NUMBER(38,0), 
	"EXECUTOR_TIPO_TEXTO" VARCHAR2(30 BYTE), 
	"ACAO_EXECUTADA" NUMBER(38,0) NOT NULL ENABLE, 
	"DATA_EXECUCAO" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_HST_CNF_FISC_INFRACAO_DEST" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_HST_CNF_FISC_INFR_DEST_ACAO" FOREIGN KEY ("ACAO_EXECUTADA")
	  REFERENCES "IDAF"."LOV_HISTORICO_ARTEFATOS_ACOES" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."ID" IS 'Chave primária. Utiliza a sequência seq_hst_cnf_fisc_infr_destin.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."DESTINACAO_ID" IS 'Chave estrangeira para cnf_fisc_infr_destinacao.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."DESTINO" IS 'Destinação.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."ATIVO" IS 'Ativo: 1 - sim | 0 - não.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."EXECUTOR_ID" IS 'Chave estrangeira para tab_funcionario. Campo (ID).';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."EXECUTOR_TID" IS 'Referencia ao campo (TID) da tabela tab_funcionario.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."EXECUTOR_NOME" IS 'Nome do executor que executou a ação.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."EXECUTOR_LOGIN" IS 'Login do executor que executou a ação.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."EXECUTOR_TIPO_ID" IS 'Chave estrangeira para lov_executor_tipo. Campo(ID).';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."EXECUTOR_TIPO_TEXTO" IS 'Texto do tipo do executor que executou a ação.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."ACAO_EXECUTADA" IS 'Ação que foi disparada pelo sistema a qual gerou essa linha de histórico.';
   COMMENT ON COLUMN "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"."DATA_EXECUCAO" IS 'Data que foi gerada essa linha de histórico.';

   COMMENT ON TABLE "IDAF"."HST_CNF_FISC_INFR_DESTINACAO"  IS 'Tabela do historico da Configuracao de Fiscalizacao - Destinação.';
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_D_EXEC_ACAO2" ON "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" ("ACAO_EXECUTADA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_D_EXEC_DATA2" ON "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" ("DATA_EXECUCAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_D_EXEC_TID2" ON "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" ("EXECUTOR_TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_D_EXE_TIP_I1" ON "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" ("EXECUTOR_TIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_D_TID2" ON "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_HST_CNF_F_INF_D_TIPO_ID2" ON "IDAF"."HST_CNF_FISC_INFR_DESTINACAO" ("DESTINACAO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
