/* SCRIPT CRIADO POR CINTHIA MEIRELES
 * DEMANDA IDAF-0034
 * 10/2019*/

CREATE TABLE "IDAF"."LOV_VALOR_DOCS_VRTE"(
"ID" NUMBER(38,0) NOT NULL ENABLE, 
"DOCUMENTO" VARCHAR2(50) NOT NULL ENABLE, 
"VALOR_VRTE" NUMBER NOT NULL ENABLE, 
CONSTRAINT "PK_LOV_VALOR_DOCS_VRTE" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "IDAF_TBS"  ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "IDAF_TBS" ;
 

COMMENT ON COLUMN "IDAF"."LOV_VALOR_DOCS_VRTE"."ID" IS 'Chave primaria.';
COMMENT ON COLUMN "IDAF"."LOV_VALOR_DOCS_VRTE"."DOCUMENTO" IS 'Tipo de documento.';
COMMENT ON COLUMN "IDAF"."LOV_VALOR_DOCS_VRTE"."VALOR_VRTE" IS 'Valor do documento, em VRTE.';
COMMENT ON TABLE "IDAF"."LOV_VALOR_DOCS_VRTE"  IS 'Valores dos documentos em VRTE.';

COMMENT ON TABLE "IDAF"."CNF_VALOR_DUA"  IS 'Esta tabela não é mais utilizada. Antiga configuração do valor anual do DUA.';

INSERT INTO LOV_VALOR_DOCS_VRTE (ID, DOCUMENTO, VALOR_VRTE) VALUES (1, 'PTV', 5);
INSERT INTO LOV_VALOR_DOCS_VRTE (ID, DOCUMENTO, VALOR_VRTE) VALUES (2, 'CFO/CFOC', 7.5);

select * from LOV_VALOR_DOCS_VRTE;