/* SCRIPT CRIADO POR CINTHIA MEIRELES
 * DEMANDA IDAF-0034
 * 10/2019*/

CREATE TABLE "IDAFCREDENCIADO"."TAB_DUA_PTV"(
"ID" NUMBER(38,0) NOT NULL ENABLE, 
"DUA" VARCHAR2(50) NOT NULL ENABLE, 
"CPF_CNPJ" VARCHAR2(50) NOT NULL ENABLE,
"SALDO_INICIAL" NUMBER(38,0) NOT NULL ENABLE,
CONSTRAINT "PK_TAB_DUA_PTV" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "IDAFCREDENCIADO_TBS"  ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "IDAFCREDENCIADO_TBS" ;
 

COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_DUA_PTV"."ID" IS 'Chave primaria.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_DUA_PTV"."DUA" IS 'Número do DUA.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_DUA_PTV"."CPF_CNPJ" IS 'CPF ou CNPJ relacionado ao DUA.';
COMMENT ON COLUMN "IDAFCREDENCIADO"."TAB_DUA_PTV"."SALDO_INICIAL" IS 'Número de PTVs comprados com o DUA.';
COMMENT ON TABLE  "IDAFCREDENCIADO"."TAB_DUA_PTV"  IS 'Tabela para armazenamento dos números de DUA para compra de PTV utilizados, e seus respectivos saldos iniciais, em número de PTVs.';

CREATE SEQUENCE SEQ_TAB_DUA_PTV INCREMENT BY 1 START WITH 1 NOMAXVALUE MINVALUE 1 NOCACHE;