
  CREATE TABLE "IDAF"."TAB_FISC_MULTA" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"FISCALIZACAO" NUMBER(38,0) NOT NULL ENABLE,
	"VALOR_MULTA" NUMBER, 
	"ARQUIVO" NUMBER(38,0), 
	"JUSTIFICAR" VARCHAR2(1000 BYTE), 
	"CODIGO_RECEITA" NUMBER(38,0), 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FIS_MUL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_FIS_MUL_FIS" FOREIGN KEY ("FISCALIZACAO")
	  REFERENCES "IDAF"."TAB_FISCALIZACAO" ("ID") ENABLE,
	 CONSTRAINT "FK_FIS_MUL_CRC" FOREIGN KEY ("CODIGO_RECEITA")
	  REFERENCES "IDAF"."LOV_FISC_INFRACAO_CODIGO_RECE" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_MUL_ARQ" FOREIGN KEY ("ARQUIVO")
	  REFERENCES "IDAF"."TAB_ARQUIVO" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."ID" IS 'Chave primaria. Utiliza a sequencia seq_tab_fisc_multa.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."FISCALIZACAO" IS 'Chave estrangeira para tab_fiscalizacao. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."VALOR_MULTA" IS 'Valor da multa.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."ARQUIVO" IS 'Chave estrangeira para tab_arquivo. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."JUSTIFICAR" IS 'Justificar o valor da penalidade pecuniaria atribuida, levando-se em considerção os parametros legais.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."CODIGO_RECEITA" IS 'Chave estrangeira para lov_fisc_infracao_codigo_rece. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_MULTA"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_FISC_MULTA"  IS 'Tabela da Fiscalização de multa.';
 

  CREATE INDEX "IDAF"."IDX_FIS_MUL_ARQ" ON "IDAF"."TAB_FISC_MULTA" ("ARQUIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_MUL_CRC" ON "IDAF"."TAB_FISC_MULTA" ("CODIGO_RECEITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_MUL_FIS" ON "IDAF"."TAB_FISC_MULTA" ("FISCALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_MUL_TID" ON "IDAF"."TAB_FISC_MULTA" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
