
  CREATE TABLE "IDAF"."TAB_FISC_OUTRAS_PENALIDADES" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"FISCALIZACAO" NUMBER(38,0) NOT NULL ENABLE, 
  "IUF_DIGITAL" NUMBER(1,0) NOT NULL ENABLE, 
	"IUF_NUMERO" NUMBER(38,0), 
	"IUF_DATA" DATE, 
	"SERIE" NUMBER(38,0),
	"DESCRICAO" VARCHAR2(3000 BYTE), 
  "ARQUIVO" NUMBER(38,0), 
	"TID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FIS_PEN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS"  ENABLE, 
	 CONSTRAINT "FK_FIS_PEN_FIS" FOREIGN KEY ("FISCALIZACAO")
	  REFERENCES "IDAF"."TAB_FISCALIZACAO" ("ID") ENABLE,
     CONSTRAINT "FK_FIS_PEN_SER" FOREIGN KEY ("SERIE")
	  REFERENCES "IDAF"."LOV_FISCALIZACAO_SERIE" ("ID") ENABLE, 
    CONSTRAINT "FK_FIS_PEN_ARQ" FOREIGN KEY ("ARQUIVO")
	  REFERENCES "IDAF"."TAB_ARQUIVO" ("ID") ENABLE
	 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."ID" IS 'Chave primaria. Utiliza a sequencia seq_fisc_outras_penalidades.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."FISCALIZACAO" IS 'Chave estrangeira para tab_fiscalizacao. Campo(ID).';
   
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."IUF_DIGITAL" IS 'Informa se IUF é digital ou bloco. 1 - digital | 0 - bloco.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."IUF_NUMERO" IS 'Informa o número do IUF.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."IUF_DATA" IS 'Data do IUF.';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."SERIE" IS 'Chave estrangeira para lov_fiscalizacao_serie. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."DESCRICAO" IS 'Descrição da penalidade.';
   
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."ARQUIVO" IS 'Chave estrangeira para tab_arquivo. Campo(ID).';
 
   COMMENT ON COLUMN "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
 
   COMMENT ON TABLE "IDAF"."TAB_FISC_OUTRAS_PENALIDADES"  IS 'Tabela da Fiscalização de outras penalidades.';
 

  CREATE INDEX "IDAF"."IDX_FIS_PEN_ARQ" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDADES" ("ARQUIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_FIS_PEN_FIS" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDADES" ("FISCALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  
  CREATE INDEX "IDAF"."IDX_FIS_PEN_SER" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDADES" ("SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 

  CREATE INDEX "IDAF"."IDX_FIS_PEN_TID" ON "IDAF"."TAB_FISC_OUTRAS_PENALIDADES" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
 
