  CREATE TABLE "IDAF"."TAB_FISC_COB_DUA"
  (
    "ID"                NUMBER(38,0) NOT NULL ENABLE,
    "VENCIMENTO_DATA" 	DATE,
    "DATAEMISSAO" 	    DATE,
    "PARCELA"           VARCHAR2(36 BYTE),    
    "NUMERO_DUA"        NUMBER(38,0),
    "VALOR_DUA"         NUMBER,
    "VALOR_PAGO"        NUMBER,
    "VRTE"              NUMBER(5,0) NOT NULL ENABLE,
    "PAGAMENTO_DATA"    DATE,
    "COMPLEMENTO"       VARCHAR2(80 BYTE),    
    "PAI_DUA"           NUMBER(38,0),    
    "COB_PARC"          NUMBER(38,0) NOT NULL ENABLE,    
    "TID"               VARCHAR2(36 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_FIS_COB_DUA" PRIMARY KEY ("ID") 
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
    TABLESPACE "IDAF_TBS" ENABLE, 
	 CONSTRAINT "FK_FIS_COB_DUA_PAI" FOREIGN KEY ("PAI_DUA")
	  REFERENCES "IDAF"."TAB_FISC_COB_DUA" ("ID") ENABLE, 
	 CONSTRAINT "FK_FIS_COB_DUA_PARC" FOREIGN KEY ("COB_PARC")
	  REFERENCES "IDAF"."TAB_FISC_COB_PARCELAMENTO" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "IDAF_TBS" ;
 
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."ID" IS 'Chave primaria. Utiliza a sequencia seq_fisc_cobranca.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."VENCIMENTO_DATA" IS 'Data de vencimento da primeira parcela.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."DATAEMISSAO" IS 'Data de emissão da cobrança.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."PARCELA" IS 'Informa a ordem da parcela dentro de um parcelamento.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."NUMERO_DUA" IS 'Informa o número do DUA.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."VALOR_DUA" IS 'Informa o valor do DUA.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."VALOR_PAGO" IS 'Informa o valor pago do DUA.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."VRTE" IS 'Informa a quantidade a ser paga em VRTE.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."PAGAMENTO_DATA" IS 'Informa a data de pagamento.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."COMPLEMENTO" IS 'Informações complementares do DUA.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."PAI_DUA" IS 'Informa o DUA(parcela) que orginou esta.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."COB_PARC" IS 'Informa o Parcelamento que este DUA(parcela) está inserido.';
  COMMENT ON COLUMN "IDAF"."TAB_FISC_COB_DUA"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
  COMMENT ON TABLE "IDAF"."TAB_FISC_COB_DUA"  IS 'Tabela de DUA.';
 
  CREATE INDEX "IDAF"."IDX_FIS_COB_DUA_TID" ON "IDAF"."TAB_FISC_COB_DUA" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;

  CREATE INDEX "IDAF"."IDX_FIS_COB_DUA_PAI" ON "IDAF"."TAB_FISC_COB_DUA" ("PAI_DUA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  CREATE INDEX "IDAF"."IDX_FIS_COB_DUA_PARC" ON "IDAF"."TAB_FISC_COB_DUA" ("COB_PARC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;