  CREATE TABLE "IDAF"."TAB_FISC_PARAM_DETALHE"
  (
    "ID"                NUMBER(38,0) NOT NULL ENABLE,
    "PARAMETRIZACAO"     NUMBER(38,0) NOT NULL ENABLE,
    "MAXIMOPARCELAS"    NUMBER(2,0) NOT NULL ENABLE,
    "VALORINICIAL"    NUMBER(15,2) NOT NULL ENABLE,
    "VALORFINAL"    NUMBER(15,2) NOT NULL ENABLE,
    "TID"              VARCHAR2(36 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_FIS_PAR_DET" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IDAF_TBS" ENABLE,
    CONSTRAINT "FK_FIS_PAR_DET_PAR" FOREIGN KEY ("PARAMETRIZACAO") REFERENCES "IDAF"."TAB_FISC_PARAMETRIZACAO" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "IDAF_TBS" ;
 
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAM_DETALHE"."ID" IS 'Chave primaria. Utiliza a sequencia seq_fisc_parametrizacao.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAM_DETALHE"."PARAMETRIZACAO" IS 'Chave estrangeira para tab_fisc_parametrizacao. Campo(ID).';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAM_DETALHE"."MAXIMOPARCELAS" IS 'Informa o número máximo de parcelas permitido.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAM_DETALHE"."VALORINICIAL" IS 'Informa o valor inicial do detalhe da parametrização.';

  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAM_DETALHE"."VALORFINAL" IS 'Informa o valor final do detalhe da parametrização.';
  
  COMMENT ON COLUMN "IDAF"."TAB_FISC_PARAM_DETALHE"."TID" IS 'Id transacional. Esse valor garante a ligação entre todas as tabelas relacionadas com essa transaction.';
  
  COMMENT ON TABLE "IDAF"."TAB_FISC_PARAMETRIZACAO"  IS 'Tabela de parametrização financeira.';
 
  CREATE INDEX "IDAF"."IDX_FIS_PAR_DET_PAR" ON "IDAF"."TAB_FISC_PARAM_DETALHE" ("PARAMETRIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
  
  
  CREATE INDEX "IDAF"."IDX_FIS_PAR_DET_TID" ON "IDAF"."TAB_FISC_PARAM_DETALHE" ("TID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IDAF_TBS" ;
