ALTER TABLE TAB_FISC_LOCAL_INFRACAO ADD ASSINANTE NUMBER(38,0);
COMMENT ON COLUMN "IDAF"."TAB_FISC_LOCAL_INFRACAO"."ASSINANTE" IS 'Chave estrangeira para tab_pessoa. Campo(ID).';
ALTER TABLE TAB_FISC_LOCAL_INFRACAO ADD CONSTRAINT "FK_FISC_LOCAL_INF_ASS" FOREIGN KEY ("ASSINANTE")
      REFERENCES "IDAF"."TAB_PESSOA" ("ID") ENABLE;
CREATE INDEX "IDAF"."IDX_TAB_FISC_LOCAL_INFASS" ON "IDAF"."TAB_FISC_LOCAL_INFRACAO" ("ASSINANTE") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "IDAF_TBS" ;    

COMMIT;